name = "Taxonomy"
uuid = "60a7ea71-f676-45d4-8f01-1d966440d6a4"
authors = ["michael catchen <michael.catchen@colorado.edu>"]
version = "0.0.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
NCBITaxonomy = "f88b31d2-eb98-4433-b52d-2dd32bc6efce"
Phylo = "aea672f4-3940-5932-aa44-993d1c3ff149"
